routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\FormController;
use App\Http\Controllers\MenuController;
use App\Http\Controllers\PpidController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\IrbanController;
use App\Http\Controllers\AgendaController;
use App\Http\Controllers\BannerController;
use App\Http\Controllers\BeritaController;
use App\Http\Controllers\LaporanController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\GalerifotoController;
use App\Http\Controllers\DatapegawaiController;
use App\Http\Controllers\GaleriVideoController;
use App\Http\Controllers\LinkTerkaitController;
use App\Http\Controllers\SaberpungliController;


// GENERAL
Route::controller(DashboardController::class)->group(function () {
    Route::get('/', 'index');
    Route::get('/berita/{slug}', 'detailberita');
    Route::get('/banner/{slug}', 'banner');
    Route::get('/agenda/{slug}', 'agenda');
    Route::get('/agenda', 'agend')->name('agend');
    Route::get('/berita', 'berita')->name('berta');
    Route::post('/comment/{idberita}', 'comment');
    Route::get('/ppid', 'ppid');
    Route::get('/saberpungli', 'saberpungli');
    Route::get('/ppid/{jenis}', 'informasi');
    Route::get('/irban/{irban}', 'irban');
});
Route::controller(FormController::class)->group(function () {
    Route::get('/forminformasi', 'forminformasi');
    Route::post('/forminformasi', 'storedinformasi');
    Route::get('/formkeberatan', 'formkeberatan');
    Route::post('/formkeberatan', 'storedkeberatan');
    Route::get('/formsaberpungli', 'formsaberpungli');
    Route::post('/formsaberpungli', 'storedsaberpungli');
    Route::get('/cek-laporan', 'ceklaporan');
    Route::post('/cek-laporan', 'carilaporan');
    Route::get('/cek-laporan/{jenis}/{id}', 'balasan')->name('balasan');
});

Route::get('/admin', [ AdminController::class, 'index'])->middleware('auth');

// ADMIN'S ROUTE
Route::prefix('admin')->middleware('auth')->group(function () {
    Route::resource('linkterkait', LinkTerkaitController::class);
    Route::resource('menu', MenuController::class);
    Route::resource('berita', BeritaController::class);
    Route::resource('banner', BannerController::class);
    Route::resource('datapegawai', DatapegawaiController::class);
    Route::resource('galerifoto', GalerifotoController::class);
    Route::resource('galerivideo', GaleriVideoController::class);
    Route::get('saberpungli', [ SaberpungliController::class, 'index']);
    Route::get('saberpungli/{id}/edit', [ SaberpungliController::class, 'edit']);
    Route::patch('saberpungli/{id}',[ SaberpungliController::class, 'storetampilan']);
    Route::resource('agenda', AgendaController::class);
    Route::get('ppid', [PpidController::class, 'vie']);
    Route::post('ppid', [PpidController::class, 'store']);
    Route::prefix('ppid')->group(function () {
        Route::resource('kelolainformasi', PpidController::class);
        Route::get('kelolatampilan', [PpidController::class, 'tampilan']);
        Route::get('kelolatampilan/{id}', [PpidController::class, 'edittampilan']);
        Route::patch('kelolatampilan/{id}', [PpidController::class, 'storetampilan']);
    });

    Route::get('/irban', [IrbanController::class, 'irban']);
    Route::prefix('irban')->group(function () {
        Route::get('{irban}', [IrbanController::class, 'index'])->name('irban');
        Route::get('{irban}/{jenis}/edit', [IrbanController::class, 'edit']);
        Route::patch('{irban}/{jenis}', [IrbanController::class, 'update']);
        Route::get('{irban}/agenda', [IrbanController::class, 'agenda'])->name('irb');
        Route::get('{irban}/agenda/create', [IrbanController::class, 'agendacreate']);
        Route::post('{irban}/agenda', [IrbanController::class, 'agendastore']);
        Route::post('{irban}/agenda/{id}/edit', [IrbanController::class, 'agendaedit']);
        Route::patch('{irban}/agenda/{id}', [IrbanController::class, 'agendaupdate']);
        Route::get('{irban}/agenda/{id}', [IrbanController::class, 'agendadestroy']);
        Route::get('{irban}/capaiankinerja', [IrbanController::class, 'capaiankinerja']);
 });

    Route::get('laporan', [LaporanController::class, 'index']);
    Route::prefix('laporan')->group(function () {
        Route::get('ppid', [LaporanController::class, 'ppid']);
        Route::get('ppid/{jenis}/{id}/balasan', [LaporanController::class, 't']);
        Route::post('ppid/{jenis}/{id}/balasan', [LaporanController::class, 'balas']);
        Route::get('ppid/{jenis}/{id}', [LaporanController::class, 'lihat']);
        Route::get('saberpungli', [LaporanController::class, 'saberpungli']);
        Route::get('saberpungli/{id}', [LaporanController::class, 'lsaberpungli']);
        Route::get('saberpungli/{id}/balasan', [LaporanController::class, 'lihatsaberpungli']);
        Route::post('saberpungli/{id}/balasan', [LaporanController::class, 'storedsaberpungli']);
    });
});

require __DIR__.'/auth.php';


// Route::get('/admin/irban1/capaiankinerja', function () {

// });

// Route::get('/admin/irban1/capaiankinerja/create', function () {
//     return view('admin.irban.irban1.createcapaian');
// });

app/Models/Menu.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Menu extends Model
{
    use HasFactory;
    protected $fillable = [
        'judul','link','gm',
    ];
}

app/Http/Controllers/MenuController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Menu;
use Redirect;
Use Alert;
class MenuController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $menu = Menu::paginate(15);
        $title = 'Hapus Menu!';
        $text = "Apakah Anda Yakin Ingin Menghapus Menu?";
        confirmDelete($title, $text);
        return view('admin.menu.index', compact('menu'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('admin.menu.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $request->validate([
            'judul' => 'required|max:255',
            'link' => 'required',
            'gm' => 'required',
        ]);
        $input = $request->all();
        Menu::create($input);
        Alert::success('Berhasil Menambahkan Menu', 'Berhasil Menambahkan Menu');
        return redirect('/admin/menu');
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
      
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $menu = Menu::findOrFail($id);
        return view('admin.menu.edit', compact('menu'));
       
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $input = [
            'judul' =>$request->judul,
            'link' => $request->link,
            'gm' => $request->gm,
        ];
        Menu::where('id', $id)->update($input);
        Alert::success('Berhasil', 'Berhasil Mengupdate Menu');
        return redirect('/admin/menu');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $menu = Menu::findOrFail($id);
        $menu->delete();
        Alert::success('Berhasil', 'Berhasil Menghapus Menu');
        return redirect('/admin/menu');
    }
}

resources/views/admin/menu/create.blade.php
@extends('layout.admin')
@section('content')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.7.0/datepicker.min.js"></script>
    <section class="bg-white dark:bg-gray-900 mt-5 ">
        <div class="max-w-2xl  py-10 mx-auto lg:py-16">
            <h2 class="mb-4 text-3xl  font-bold text-gray-900 dark:text-white text-center">Tambah Berita</h2>
            <form action="/admin/menu" method="post">
                @csrf
                <div class="grid gap-3 mb-4 sm:grid-cols-2 sm:gap-6 sm:mb-5">
                    <div class="sm:col-span-2">
                        <label for="name" class="block mb-2 text-lg font-medium text-gray-900 dark:text-white">Judul
                            Menu</label>
                        <input type="text" name="judul" id="name"
                            class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500"
                            placeholder="Masukkan Judul Menu...">
                    </div>


                    <div class="sm:col-span-2">
                        <label for="name" class="block mb-2 text-lg font-medium text-gray-900 dark:text-white">Link
                            Drive</label>
                        <input type="text" name="link" id="name"
                            class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500"
                            placeholder="Masukkan Link Drive...">
                    </div>

                    <div class="sm:col-span-2">
                        <label for="countries" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Pilih Menu</label>
                        <select id="countries" name="gm"
                            class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
                            <option value="profile" selected>Profile</option>
                            <option value="regulasi">Regulasi</option>
                            <option value="pedoman standar">Pedoman Standar</option>
                        </select>
                    </div>

                    {{-- <div class="flex items-center ">
                        <input checked id="checked-checkbox" type="checkbox" value=""
                            class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600">
                        <label for="checked-checkbox"
                            class="ml-2 text-sm font-medium text-gray-900 dark:text-gray-300">Submenu</label>

                        <!-- Modal toggle -->
                        <button data-modal-target="defaultModal" data-modal-toggle="defaultModal"
                            class="block text-white  focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
                            type="button">
                            <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M8 9h2v5m-2 0h4M9.408 5.5h.01M19 10a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"/>
                              </svg>
                        </button>

                        <!-- Main modal -->
                        <div id="defaultModal" tabindex="-1" aria-hidden="true"
                            class="fixed top-0 left-0 right-0 z-50 hidden w-full p-4 overflow-x-hidden overflow-y-auto md:inset-0 h-[calc(100%-1rem)] max-h-full">
                            <div class="relative w-full max-w-2xl max-h-full">
                                <!-- Modal content -->
                                <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
                                    <!-- Modal header -->
                                    <div
                                        class="flex items-start justify-between p-4 border-b rounded-t dark:border-gray-600">
                                        <h3 class="text-xl font-semibold text-gray-900 dark:text-white">
                                            Terms of Service
                                        </h3>
                                        <button type="button"
                                            class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ml-auto inline-flex justify-center items-center dark:hover:bg-gray-600 dark:hover:text-white"
                                            data-modal-hide="defaultModal">
                                            <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg"
                                                fill="none" viewBox="0 0 14 14">
                                                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                                                    stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6" />
                                            </svg>
                                            <span class="sr-only">Close modal</span>
                                        </button>
                                    </div>
                                    <!-- Modal body -->
                                    <div class="p-6 space-y-6">
                                        <p class="text-base leading-relaxed text-gray-500 dark:text-gray-400">
                                            With less than a month to go before the European Union enacts new consumer
                                            privacy laws for its citizens, companies around the world are updating their
                                            terms of service agreements to comply.
                                        </p>
                                        <p class="text-base leading-relaxed text-gray-500 dark:text-gray-400">
                                            The European Union’s General Data Protection Regulation (G.D.P.R.) goes into
                                            effect on May 25 and is meant to ensure a common set of data rights in the
                                            European Union. It requires organizations to notify users as soon as possible of
                                            high-risk data breaches that could personally affect them.
                                        </p>
                                    </div>
                                    <!-- Modal footer -->
                                    <div
                                        class="flex items-center p-6 space-x-2 border-t border-gray-200 rounded-b dark:border-gray-600">
                                        <button data-modal-hide="defaultModal" type="button"
                                            class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">I
                                            accept</button>
                                        <button data-modal-hide="defaultModal" type="button"
                                            class="text-gray-500 bg-white hover:bg-gray-100 focus:ring-4 focus:outline-none focus:ring-blue-300 rounded-lg border border-gray-200 text-sm font-medium px-5 py-2.5 hover:text-gray-900 focus:z-10 dark:bg-gray-700 dark:text-gray-300 dark:border-gray-500 dark:hover:text-white dark:hover:bg-gray-600 dark:focus:ring-gray-600">Decline</button>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div> --}}

                </div>
                <div class="flex items-center space-x-4">
                    <button type="submit"
                        class="text-white bg-[#063A69] hover:bg-primary-800 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800">
                        Submit
                    </button>

                </div>
            </form>
        </div>
    </section>
@endsection

resources/views/admin/menu/index.blade.php
@extends('layout.admin')
@section('content')
<section class="bg-gray-50 dark:bg-gray-900 ">
    <div class="mx-auto max-w-screen-xl  ">
        <!-- Start coding here -->
        <div class="bg-white dark:bg-gray-800 relative shadow-md sm:rounded-lg overflow-hidden">
            <div class="flex flex-col md:flex-row items-center justify-between space-y-3 md:space-y-0 md:space-x-4 p-4">
                <div class="w-full md:w-1/2">
                    <p class="text-2xl font-semibold text-[#063A69]">Menu Inspektorat</p>
                </div>
                <div
                    class="w-full md:w-auto flex flex-col md:flex-row space-y-2 md:space-y-0 items-stretch md:items-center justify-end md:space-x-3 flex-shrink-0">
                    <a href="/admin/menu/create">
                        <button type="button"
                            class="flex items-center justify-center text-white bg-[#214E6D] hover:bg-primary-800 focus:ring-4 focus:ring-primary-300 font-medium rounded-lg text-sm px-4 py-2 dark:bg-primary-600 dark:hover:bg-primary-700 focus:outline-none dark:focus:ring-primary-800">
                            <svg class="h-3.5 w-3.5 mr-2" fill="currentColor" viewbox="0 0 20 20"
                                xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
                                <path clip-rule="evenodd" fill-rule="evenodd"
                                    d="M10 3a1 1 0 011 1v5h5a1 1 0 110 2h-5v5a1 1 0 11-2 0v-5H4a1 1 0 110-2h5V4a1 1 0 011-1z" />
                            </svg>
                            Tambah Menu
                        </button>
                    </a>

                </div>
            </div>
            <div class="overflow-x-auto mt-3">
                <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
                    <thead class="text text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                        <tr>
                            <th scope="col" class="px-4 py-3" width="30%">Judul</th>
                            <th scope="col" class="px-4 py-3">Link</th>
                            <th scope="col" class="px-4 py-3">View</th>
                            <th scope="col" class="px-4 py-3">Comment</th>
                            <th scope="col" class="px-4 py-3">Tanggal</th>
                            <th scope="col" class="px-4 py-3">
                                <span class="sr-only">Actions</span>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($menu as $item)
                            
                        <tr class="border-b dark:border-gray-700">
                            <th scope="row"
                                class="px-4 py-3 font-medium text-gray-900 whitespace-nowrap dark:text-white">{{$item->judul}}</th>
                            <td class="px-4 py-3"><a href="{{$item->link}}" target="_blank">{{$item->link}}</a></td>
                            <td class="px-4 py-3">100</td>
                            <td class="px-4 py-3">4</td>
                            <td class="px-4 py-3">10 November 2023</td>
                            <td class="px-4 py-3 flex items-center justify-end">
                                <button id="apple-imac-27-dropdown-button" data-dropdown-toggle="{{$item->id}}"
                                    class="inline-flex items-center p-0.5 text-sm font-medium text-center text-gray-500 hover:text-gray-800 rounded-lg focus:outline-none dark:text-gray-400 dark:hover:text-gray-100"
                                    type="button">
                                    <svg class="w-5 h-5" aria-hidden="true" fill="currentColor" viewbox="0 0 20 20"
                                        xmlns="http://www.w3.org/2000/svg">
                                        <path
                                            d="M6 10a2 2 0 11-4 0 2 2 0 014 0zM12 10a2 2 0 11-4 0 2 2 0 014 0zM16 12a2 2 0 100-4 2 2 0 000 4z" />
                                    </svg>
                                </button>
                                <div id="{{$item->id}}"
                                    class="hidden z-10 w-44 bg-white rounded divide-y divide-gray-100 shadow dark:bg-gray-700 dark:divide-gray-600">
                                    <ul class="py-1 text-sm text-gray-700 dark:text-gray-200"
                                        aria-labelledby="apple-imac-27-dropdown-button">
                                        <li>
                                            <a href="#"
                                                class="block py-2 px-4 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Tampil</a>
                                        </li>
                                        <li>
                                            <a href="/admin/menu/{{$item->id}}/edit"
                                                class="block py-2 px-4 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Edit</a>
                                        </li>
                                    </ul>
                                    <div class="py-1">
                                        <a href="{{ route('menu.destroy', $item->id) }}" data-confirm-delete="true"
                                            class="block py-2 px-4 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Hapus</a>
                                    </div>
                                </div>
                            </td>
                        </tr>
                        @endforeach

                    </tbody>
                </table>
            </div>
            <nav class="flex flex-col md:flex-row justify-between items-start md:items-center space-y-3 md:space-y-0 p-4"
                aria-label="Table navigation">
                <span class="text-sm font-normal text-gray-500 dark:text-gray-400">
                    Showing
                    <span class="font-semibold text-gray-900 dark:text-white">1-10</span>
                    of
                    <span class="font-semibold text-gray-900 dark:text-white">1000</span>
                </span>
                <ul class="inline-flex items-stretch -space-x-px">
                    <li>
                        <a href="#"
                            class="flex items-center justify-center h-full py-1.5 px-3 ml-0 text-gray-500 bg-white rounded-l-lg border border-gray-300 hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">
                            <span class="sr-only">Previous</span>
                            <svg class="w-5 h-5" aria-hidden="true" fill="currentColor" viewbox="0 0 20 20"
                                xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd"
                                    d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z"
                                    clip-rule="evenodd" />
                            </svg>
                        </a>
                    </li>
                    <li>
                        <a href="#"
                            class="flex items-center justify-center text-sm py-2 px-3 leading-tight text-gray-500 bg-white border border-gray-300 hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">1</a>
                    </li>
                    <li>
                        <a href="#"
                            class="flex items-center justify-center text-sm py-2 px-3 leading-tight text-gray-500 bg-white border border-gray-300 hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">2</a>
                    </li>
                    <li>
                        <a href="#" aria-current="page"
                            class="flex items-center justify-center text-sm z-10 py-2 px-3 leading-tight text-primary-600 bg-primary-50 border border-primary-300 hover:bg-primary-100 hover:text-primary-700 dark:border-gray-700 dark:bg-gray-700 dark:text-white">3</a>
                    </li>
                    <li>
                        <a href="#"
                            class="flex items-center justify-center text-sm py-2 px-3 leading-tight text-gray-500 bg-white border border-gray-300 hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">...</a>
                    </li>
                    <li>
                        <a href="#"
                            class="flex items-center justify-center text-sm py-2 px-3 leading-tight text-gray-500 bg-white border border-gray-300 hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">100</a>
                    </li>
                    <li>
                        <a href="#"
                            class="flex items-center justify-center h-full py-1.5 px-3 leading-tight text-gray-500 bg-white rounded-r-lg border border-gray-300 hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">
                            <span class="sr-only">Next</span>
                            <svg class="w-5 h-5" aria-hidden="true" fill="currentColor" viewbox="0 0 20 20"
                                xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd"
                                    d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z"
                                    clip-rule="evenodd" />
                            </svg>
                        </a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
</section>
@endsection