routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\FormController;
use App\Http\Controllers\MenuController;
use App\Http\Controllers\PpidController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\IrbanController;
use App\Http\Controllers\AgendaController;
use App\Http\Controllers\BannerController;
use App\Http\Controllers\BeritaController;
use App\Http\Controllers\LaporanController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\GalerifotoController;
use App\Http\Controllers\DatapegawaiController;
use App\Http\Controllers\GaleriVideoController;
use App\Http\Controllers\LinkTerkaitController;
use App\Http\Controllers\SaberpungliController;


// GENERAL
Route::controller(DashboardController::class)->group(function () {
    Route::get('/', 'index');
    Route::get('/berita/{slug}', 'detailberita');
    Route::get('/banner/{slug}', 'banner');
    Route::get('/agenda/{slug}', 'agenda');
    Route::get('/agenda', 'agend')->name('agend');
    Route::get('/berita', 'berita')->name('berta');
    Route::post('/comment/{idberita}', 'comment');
    Route::get('/ppid', 'ppid');
    Route::get('/saberpungli', 'saberpungli');
    Route::get('/ppid/{jenis}', 'informasi');
    Route::get('/irban/{irban}', 'irban');
});
Route::controller(FormController::class)->group(function () {
    Route::get('/forminformasi', 'forminformasi');
    Route::post('/forminformasi', 'storedinformasi');
    Route::get('/formkeberatan', 'formkeberatan');
    Route::post('/formkeberatan', 'storedkeberatan');
    Route::get('/formsaberpungli', 'formsaberpungli');
    Route::post('/formsaberpungli', 'storedsaberpungli');
    Route::get('/cek-laporan', 'ceklaporan');
    Route::post('/cek-laporan', 'carilaporan');
    Route::get('/cek-laporan/{jenis}/{id}', 'balasan')->name('balasan');
});

Route::get('/admin', [ AdminController::class, 'index'])->middleware('auth');

// ADMIN'S ROUTE
Route::prefix('admin')->middleware('auth')->group(function () {
    Route::resource('linkterkait', LinkTerkaitController::class);
    Route::resource('menu', MenuController::class);
    Route::resource('berita', BeritaController::class);
    Route::resource('banner', BannerController::class);
    Route::resource('datapegawai', DatapegawaiController::class);
    Route::resource('galerifoto', GalerifotoController::class);
    Route::resource('galerivideo', GaleriVideoController::class);
    Route::get('saberpungli', [ SaberpungliController::class, 'index']);
    Route::get('saberpungli/{id}/edit', [ SaberpungliController::class, 'edit']);
    Route::patch('saberpungli/{id}',[ SaberpungliController::class, 'storetampilan']);
    Route::resource('agenda', AgendaController::class);
    Route::get('ppid', [PpidController::class, 'vie']);
    Route::post('ppid', [PpidController::class, 'store']);
    Route::prefix('ppid')->group(function () {
        Route::resource('kelolainformasi', PpidController::class);
        Route::get('kelolatampilan', [PpidController::class, 'tampilan']);
        Route::get('kelolatampilan/{id}', [PpidController::class, 'edittampilan']);
        Route::patch('kelolatampilan/{id}', [PpidController::class, 'storetampilan']);
    });

    Route::get('/irban', [IrbanController::class, 'irban']);
    Route::prefix('irban')->group(function () {
        Route::get('{irban}', [IrbanController::class, 'index'])->name('irban');
        Route::get('{irban}/{jenis}/edit', [IrbanController::class, 'edit']);
        Route::patch('{irban}/{jenis}', [IrbanController::class, 'update']);
        Route::get('{irban}/agenda', [IrbanController::class, 'agenda'])->name('irb');
        Route::get('{irban}/agenda/create', [IrbanController::class, 'agendacreate']);
        Route::post('{irban}/agenda', [IrbanController::class, 'agendastore']);
        Route::post('{irban}/agenda/{id}/edit', [IrbanController::class, 'agendaedit']);
        Route::patch('{irban}/agenda/{id}', [IrbanController::class, 'agendaupdate']);
        Route::get('{irban}/agenda/{id}', [IrbanController::class, 'agendadestroy']);
        Route::get('{irban}/capaiankinerja', [IrbanController::class, 'capaiankinerja']);
 });

    Route::get('laporan', [LaporanController::class, 'index']);
    Route::prefix('laporan')->group(function () {
        Route::get('ppid', [LaporanController::class, 'ppid']);
        Route::get('ppid/{jenis}/{id}/balasan', [LaporanController::class, 't']);
        Route::post('ppid/{jenis}/{id}/balasan', [LaporanController::class, 'balas']);
        Route::get('ppid/{jenis}/{id}', [LaporanController::class, 'lihat']);
        Route::get('saberpungli', [LaporanController::class, 'saberpungli']);
        Route::get('saberpungli/{id}', [LaporanController::class, 'lsaberpungli']);
        Route::get('saberpungli/{id}/balasan', [LaporanController::class, 'lihatsaberpungli']);
        Route::post('saberpungli/{id}/balasan', [LaporanController::class, 'storedsaberpungli']);
    });
});

require __DIR__.'/auth.php';


// Route::get('/admin/irban1/capaiankinerja', function () {

// });

// Route::get('/admin/irban1/capaiankinerja/create', function () {
//     return view('admin.irban.irban1.createcapaian');
// });

app/Models/Datapegawai.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Datapegawai extends Model
{
    use HasFactory;
    
    protected $fillable = [
        'nama','jumlah'
    ];
}

app/Http/Controllers/DatapegawaiController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Datapegawai;
use RealRashid\SweetAlert\Facades\Alert;
use Cviebrock\EloquentSluggable\Services\SlugService;
class DatapegawaiController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $dataPegawai = Datapegawai::paginate(10);
        $title = 'Hapus Data Pegawai!';
        $text = "Apakah Anda Yakin Ingin Menghapus Data Pegawai?";
        confirmDelete($title, $text);
        return view('admin.datapegawai.index', compact('dataPegawai'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('admin.datapegawai.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $request->validate([
            'nama' => 'required|max:255',
            'jumlah' => 'required',
        ],
        [
            'required' => ':attribute Belum Diisi.',
        ]);
        $input = $request->all();
        Datapegawai::create($input);
        Alert::success('Berhasil', 'Berhasil Menambahkan Data Pegawai');
        return redirect('/admin/datapegawai');
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $dataPegawai = Datapegawai::findOrFail($id);
        $dataPegawai->delete();
        Alert::success('Berhasil', 'Berhasil Menghapus Data Pegawai');
        return redirect('/admin/datapegawai');
    }
}

resources/views/admin/datapegawai/create.blade.php
@extends('layout.admin')
@section('content')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.7.0/datepicker.min.js"></script>
    <section class="bg-white dark:bg-gray-900 mt-5 ">
        <div class="max-w-2xl  py-10 mx-auto lg:py-16">
            <h2 class="mb-4 text-3xl  font-bold text-gray-900 dark:text-white text-center">Tambah Data Pegawai</h2>
            <form action="/admin/datapegawai" method="POST" >
                @csrf
                <div class="grid gap-4 mb-4 sm:grid-cols-2 sm:gap-6 sm:mb-5">
                    <div class="sm:col-span-2">
                        <label for="name"  class="block mb-2 text-lg font-medium text-gray-900 dark:text-white">Data Pegawai</label>
                        <input type="text" name="nama" id="name"
                            class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500"
                            placeholder="Masukkan Nama Jabatan...">
                            @error('nama')
                            <p class="mt-2 text-sm text-red-600 dark:text-red-500 capitalize"><span class="">*Nama Jabatan Belum Diisi</p>
                            @enderror
                    </div>
                    <div class="sm:col-span-2">
                        <label for="name" class="block mb-2 text-lg font-medium text-gray-900 dark:text-white">Jumlah</label>
                        <input type="text" name="jumlah" id="name"
                            class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500"
                            placeholder="Masukkan Jumlah Pegawai...">
                            @error('jumlah')
                            <p class="mt-2 text-sm text-red-600 dark:text-red-500 capitalize"><span class="">*Jumlah Pegawai Belum Diisi</p>
                            @enderror
                            
                    </div>
                    
                <div class="flex items-center space-x-4">
                    <button type="submit"
                        class="text-white bg-[#063A69] hover:bg-primary-800 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800">
                       Submit
                    </button>
              
                </div>
            </form>
        </div>
    </section>
@endsection

resources/views/admin/datapegawai/index.blade.php
@extends('layout.admin')
@section('content')
    <section class="bg-gray-50 dark:bg-gray-900 ">
        <div class="mx-auto max-w-screen-xl  ">
            <!-- Start coding here -->
            <div class="bg-white dark:bg-gray-800 relative shadow-md sm:rounded-lg overflow-hidden">
                <div class="flex flex-col md:flex-row items-center justify-between space-y-3 md:space-y-0 md:space-x-4 p-4">
                    <div class="w-full md:w-1/2">
                        <p class="text-2xl font-semibold text-[#063A69]">Data Pegawai Inspektorat</p>
                    </div>
                    <div
                        class="w-full md:w-auto flex flex-col md:flex-row space-y-2 md:space-y-0 items-stretch md:items-center justify-end md:space-x-3 flex-shrink-0">
                        <a href="/admin/datapegawai/create">
                            <button type="button"
                                class="flex items-center justify-center text-white bg-[#214E6D] hover:bg-primary-800 focus:ring-4 focus:ring-primary-300 font-medium rounded-lg text-sm px-4 py-2 dark:bg-primary-600 dark:hover:bg-primary-700 focus:outline-none dark:focus:ring-primary-800">
                                <svg class="h-3.5 w-3.5 mr-2" fill="currentColor" viewbox="0 0 20 20"
                                    xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
                                    <path clip-rule="evenodd" fill-rule="evenodd"
                                        d="M10 3a1 1 0 011 1v5h5a1 1 0 110 2h-5v5a1 1 0 11-2 0v-5H4a1 1 0 110-2h5V4a1 1 0 011-1z" />
                                </svg>
                                Tambah Data Pegawai
                            </button>
                        </a>

                    </div>
                </div>
                <div class="overflow-x-auto mt-3">
                    <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
                        <thead class="text text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                            <tr>
                                <th scope="col" class="px-4 py-3" width="30%">Data Pegawai</th>
                                <th scope="col" class="px-4 py-3">Jumlah</th>
                                <th scope="col" class="px-4 py-3">
                                    <span class="sr-only">Actions</span>
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($dataPegawai as $item)
                            <tr class="border-b dark:border-gray-700">
                                <th scope="row"
                                    class="px-4 py-3 font-medium text-gray-900 whitespace-nowrap dark:text-white">{{$item->nama}}
                                </th>
                                <td class="px-4 py-3">{{$item->jumlah}}</td>
                                <td class="px-4 py-3 flex items-center justify-end">
                                    <button id="apple-imac-27-dropdown-button" data-dropdown-toggle="{{$item->id}}"
                                        class="inline-flex items-center p-0.5 text-sm font-medium text-center text-gray-500 hover:text-gray-800 rounded-lg focus:outline-none dark:text-gray-400 dark:hover:text-gray-100"
                                        type="button">
                                        <svg class="w-5 h-5" aria-hidden="true" fill="currentColor" viewbox="0 0 20 20"
                                            xmlns="http://www.w3.org/2000/svg">
                                            <path
                                                d="M6 10a2 2 0 11-4 0 2 2 0 014 0zM12 10a2 2 0 11-4 0 2 2 0 014 0zM16 12a2 2 0 100-4 2 2 0 000 4z" />
                                        </svg>
                                    </button>
                                    <div id="{{$item->id}}"
                                        class="hidden z-10 w-44 bg-white rounded divide-y divide-gray-100 shadow dark:bg-gray-700 dark:divide-gray-600">
                                     
                                        <div class="py-1">
                                            <a href="{{ route('datapegawai.destroy', $item->id) }}"
                                                data-confirm-delete="true" class="block py-2 px-4 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Hapus</a>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
                <nav class="flex flex-col md:flex-row justify-between items-start md:items-center space-y-3 md:space-y-0 p-4"
                    aria-label="Table navigation">
                    <span class="text-sm font-normal text-gray-500 dark:text-gray-400">
                        Showing
                        <span class="font-semibold text-gray-900 dark:text-white">1-10</span>
                        of
                        <span class="font-semibold text-gray-900 dark:text-white">1000</span>
                    </span>
                    <ul class="inline-flex items-stretch -space-x-px">
                        <li>
                            <a href="#"
                                class="flex items-center justify-center h-full py-1.5 px-3 ml-0 text-gray-500 bg-white rounded-l-lg border border-gray-300 hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">
                                <span class="sr-only">Previous</span>
                                <svg class="w-5 h-5" aria-hidden="true" fill="currentColor" viewbox="0 0 20 20"
                                    xmlns="http://www.w3.org/2000/svg">
                                    <path fill-rule="evenodd"
                                        d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z"
                                        clip-rule="evenodd" />
                                </svg>
                            </a>
                        </li>
                        <li>
                            <a href="#"
                                class="flex items-center justify-center text-sm py-2 px-3 leading-tight text-gray-500 bg-white border border-gray-300 hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">1</a>
                        </li>
                        <li>
                            <a href="#"
                                class="flex items-center justify-center text-sm py-2 px-3 leading-tight text-gray-500 bg-white border border-gray-300 hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">2</a>
                        </li>
                        <li>
                            <a href="#"
                                class="flex items-center justify-center h-full py-1.5 px-3 leading-tight text-gray-500 bg-white rounded-r-lg border border-gray-300 hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">
                                <span class="sr-only">Next</span>
                                <svg class="w-5 h-5" aria-hidden="true" fill="currentColor" viewbox="0 0 20 20"
                                    xmlns="http://www.w3.org/2000/svg">
                                    <path fill-rule="evenodd"
                                        d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z"
                                        clip-rule="evenodd" />
                                </svg>
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </section>
@endsection